Tienda/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('products.urls', namespace='products')),
    url(r'^', include('userslog.urls', namespace='userslog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.ProductList.as_view(), name='hello'),
	url(r'^product/(?P<pk>[0-9]+)/$', views.ProductDetail.as_view(), name='detail'),
	url(r'^product/new', views.new_product, name = "new"),
	
]

userslog/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^logout$', auth_views.logout, {'next_page': '/'},name="logout"),
	url(r'^login/$', views.authentication, name='authentication'),
]

Clients/models.py
from __future__ import unicode_literals
from django.db import models

class Client(models.Model):
	name = models.CharField(max_length=255)
	phone = models.IntegerField(unique=True)
	email = models.EmailField(max_length=255)
	adress = models.CharField(max_length=255)

	def __str__(self):
		return self.name

	class Meta:
		ordering = ('id',)	

employee/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Employee(models.Model):
	name = models.CharField(max_length=255)
	area = models.CharField(max_length=255)
	

	def __str__(self):
		return self.name

products/models.py
from __future__ import unicode_literals
from Clients.models import Client
from django.db import models

class Product(models.Model):
    
	description = models.CharField(max_length=255)
	category = models.CharField(max_length=255)
	price = models.DecimalField(max_digits=6,decimal_places=2)
	image = models.ImageField(blank=True)
	name = models.CharField(max_length=255)

	def __str__(self):
		return self.name

	class Meta:
		ordering = ('id',)	

class Favorite(models.Model):
	user = models.ForeignKey(Client)
	product = models.ForeignKey(Product)

	class Meta:
		verbose_name= 'Favorite'
		verbose_name_plural = 'Favorites'

	def __str__(self):
		return '%s %s' % (self.user.name, self.product.name)

userslog/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

products/forms.py
from django import forms
from .models import Product


class ProductForm(forms.ModelForm):
	class Meta:
		model = Product
		fields = '__all__'

Clients/views.py
from django.shortcuts import render

# Create your views here.

employee/views.py
from django.shortcuts import render

# Create your views here.

products/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from .models import Product
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from .forms import ProductForm
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from .mixins import LoginRequiredMixin


class ProductList(ListView):
	model = Product

class ProductDetail(DetailView):
	model = Product

@login_required()
def new_product(request):
	if request.method == 'POST':
		form = ProductForm(request.POST, request.FILES)
		if form.is_valid():
			product = form.save(commit=False)
			product.save()
			return HttpResponseRedirect('/')
	else:
		form = ProductForm()

	template = loader.get_template('new_product.html')
	context = {
		'form': form
	}
	return HttpResponse(template.render(context, request))

userslog/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.http import HttpResponse, HttpResponseRedirect

# Create your views here.
def authentication(request):
	if request.method == 'POST':
			action = request.POST.get('action', None)
			username = request.POST.get('username', None)
			password = request.POST.get('password', None)
			if action == 'login':	
			    user = authenticate(username=username, password=password)
			    login(request, user)
			return redirect('/') 

	return render(request, 'login.html', {})

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>

	{% load staticfiles %}
    <meta chatset="UTF-8">
	<title>Tienda OP</title>
	<link rel="stylesheet" href="{% static 'css/base.css' %}">
	<header id="mainHeader" ><div class="contenedor">
		
	<a href="/"><h1 class="logo">Tienda OP</h1></a>
	{% if user.is_superuser %}
	    <a href="admin/" class="botonesh">Admin</a>
	
	{% endif %}
	{% if user.is_staff %}
	    <a href="{% url "products:new" %}" class="botonesh">New Product</a>

	{% endif %}
	{% if user.is_authenticated %}   
	
	<a href="{% url "userslog:logout" %}" class="botonesh">Logout</a>
	
	{% else %}

	<a href="{% url "userslog:authentication" %}" class="botonesh">Login</a>

	{% endif %}</div></header>

</head>
<body>

    {% block content %}
	
	<ul>
		{% for pr in product %}
		    <!--<p>{{ pr.name }}</p>-->
			<a href="{% url 'products.views.product_detail' pk=pr.pk %}"><img class="img" src="{{ pr.image.url }}" alt=""></a>
			<br>
				<a href="{% url 'products.views.product_detail' pk=pr.pk %}" class="prnom">$ {{ pr.price }}  USD</a>
			<br>
		{% endfor %}
	</ul>
	{% endblock %}
</body>
</html>

templates/login.html
{% extends "index.html" %}
{% block content %}
<h1>Login</h1>
	<form action="" method="post">
		{% csrf_token %}
		<input type="hidden" name="action" value="login">

		<input type="text" name="username">
		<input type="password" name="password">

		<button type="submit" class="myButton">Login</button>
		
	</form>
	<br>
	<a href="/" title="" class="botonesg">Back</a>
{% endblock %}

templates/new_product.html
{% extends "index.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
	{% load staticfiles %}
	<meta charset="UTF-8">
	<title>New Article</title>
	<link rel="stylesheet" href="{% static 'css/base.css'%}">
</head>
<body>
	{% block content %}
	<h1>New Article</h1>
	<form method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">Submit</button>
		<a href="/"><p>Back</p></a>

	</form>
	{% endblock %}
</body>
</html>

templates/product_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% load staticfiles %}
	<meta charset="UTF-8">
	<title>{{ product.name }}</title>
	
	<link rel="stylesheet" href="{% static 'css/base.css'%}">
</head>
<body>
	<header id="productHeader"><h1 style="color:#E3F2FD">{{ product.name }}</h1>
	<h2 style="color:#E3F2FD">{{ product.description }}</h2></header>

	<p>
		{{ product.category }}  $
		{{ product.price }}
	</p>

	<img src="{{ product.image.url }}" alt="">
	<a href="/">Back</a>
</body>
</html>

templates/products/product_detail.html
{% extends "index.html" %}
{% block content %}

	<header id="productHeader"><h1>{{ product.name }}</h1>
	</header>

	<p>
		{{ product.category }}  $
		{{ product.price }}
	</p>
	
	<img src="{{ product.image.url }}" alt="">
	<a href="/" class="botonesg">Back</a>

{% endblock %}

templates/products/product_list.html
{% extends "index.html" %}


    {% block content %}
	
	<ul>
		{% for pr in object_list %}
		    <!--<p>{{ pr.name }}</p>-->
			<a href="{% url "products:detail" pr.id %}"><img class="img" src="{{ pr.image.url }}" alt=""></a>
			<br>
			<a href="{% url "products:detail" pr.id %}" class="botonesg">$ {{ pr.price }}  USD</a>	
			<br>
		{% endfor %}
	</ul>
	{% endblock %}